# Generated by Django 5.0.6 on 2024-07-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='city',
            field=models.CharField(default='Kumasi', max_length=100),
            preserve_default=False,
        ),
    ]
