# Generated by Django 5.0.6 on 2024-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_bus_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='tickets.seat'),
        ),
    ]
