# Generated by Django 5.0.6 on 2024-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
    ]
