# Generated by Django 5.1 on 2024-08-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_busoperator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busoperator',
            name='user',
        ),
    ]
