# Generated by Django 5.1 on 2024-09-02 22:31

from django.db import migrations, models
import uuid

def generate_unique_ticket_ids(apps, schema_editor):
    Booking = apps.get_model('tickets', 'Booking')
    for booking in Booking.objects.all():
        if not booking.ticket_id:
            # Generate a unique ticket_id
            booking.ticket_id = uuid.uuid4().hex[:8].upper()
            booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_busoperator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(max_length=8, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(generate_unique_ticket_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]

