# Generated by Django 5.1 on 2024-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default='A0744435', max_length=8, unique=True),
        ),
    ]
