# Generated by Django 5.1 on 2024-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_booking_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default='80166F1F', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('RefundRequested', 'RefundRequested')], max_length=20),
        ),
    ]
