# Generated by Django 5.1 on 2024-09-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_payment_refund_date_alter_booking_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default='A4446020', max_length=8, unique=True),
        ),
    ]
