# Generated by Django 5.1 on 2024-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default='C5259D19', max_length=8, unique=True),
        ),
    ]
