# Generated by Django 5.1 on 2024-09-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_busoperator_user_alter_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
